-- Script para insertar la Carta Fija de Paradero 104
-- Ejecutar en el Editor SQL de Supabase

INSERT INTO products (id, name, price, category, tenant_id) VALUES
(gen_random_uuid(), 'Cebiche de pescado', 100, 'Familiar', 'paradero'),
(gen_random_uuid(), 'Arroz c/ mariscos', 100, 'Familiar', 'paradero'),
(gen_random_uuid(), 'Cebiche mixto', 120, 'Familiar', 'paradero'),
(gen_random_uuid(), 'Chaufa de mariscos', 100, 'Familiar', 'paradero'),
(gen_random_uuid(), 'Cebiche / arroz con mariscos / chicharrón de pota', 29, 'Tríos', 'paradero'),
(gen_random_uuid(), 'Cebiche / chaufa de mariscos / chicharrón de pota', 29, 'Tríos', 'paradero'),
(gen_random_uuid(), 'Cebiche / arroz con mariscos / chicharrón de pescado', 29, 'Tríos', 'paradero'),
(gen_random_uuid(), 'Cebiche / chaufa de mariscos / chicharrón de pescado', 29, 'Tríos', 'paradero'),
(gen_random_uuid(), 'Combina tu trío (todo vale)', 45, 'Tríos', 'paradero'),
(gen_random_uuid(), 'Chilcano especial', 12, 'Sopas', 'paradero'),
(gen_random_uuid(), 'Parihuela cabrilla', 28, 'Sopas', 'paradero'),
(gen_random_uuid(), 'Parihuela de pescado (filete)', 28, 'Sopas', 'paradero'),
(gen_random_uuid(), 'Sudado cabrilla', 28, 'Sopas', 'paradero'),
(gen_random_uuid(), 'Sudado de pescado (filete)', 28, 'Sopas', 'paradero'),
(gen_random_uuid(), 'Chupe de pescado', 26, 'Sopas', 'paradero'),
(gen_random_uuid(), 'Chupe de camarones', 32, 'Sopas', 'paradero'),
(gen_random_uuid(), 'Arroz con mariscos', 27, 'Arroces', 'paradero'),
(gen_random_uuid(), 'Chaufa de mariscos', 25, 'Arroces', 'paradero'),
(gen_random_uuid(), 'Chaufa de pescado', 26, 'Arroces', 'paradero'),
(gen_random_uuid(), 'Aeropuerto marino', 26, 'Arroces', 'paradero'),
(gen_random_uuid(), 'Arroz c/ langostino', 36, 'Arroces', 'paradero'),
(gen_random_uuid(), 'Tacu tacu en salsa de mariscos', 26, 'Tacu tacu', 'paradero'),
(gen_random_uuid(), 'Tacu tacu c/ filete en salsa a lo macho', 35, 'Tacu tacu', 'paradero'),
(gen_random_uuid(), 'Tacu tacu c/ saltado de pescado', 27, 'Tacu tacu', 'paradero'),
(gen_random_uuid(), 'Tacu tacu c/ lomo saltado', 30, 'Tacu tacu', 'paradero'),
(gen_random_uuid(), 'Tacu tacu c/ saltado de pollo', 28, 'Tacu tacu', 'paradero'),
(gen_random_uuid(), 'Pescado frito cabrilla', 25, 'Pescado', 'paradero'),
(gen_random_uuid(), 'Pescado frito doncella', 18, 'Pescado', 'paradero'),
(gen_random_uuid(), 'Pescado a lo macho', 28, 'Pescado', 'paradero'),
(gen_random_uuid(), 'Filete de pescado en salsa de ajo', 26, 'Pescado', 'paradero'),
(gen_random_uuid(), 'Escabeche de pescado filete', 26, 'Pescado', 'paradero'),
(gen_random_uuid(), 'Filete de pescado a la chorrilana', 26, 'Pescado', 'paradero'),
(gen_random_uuid(), 'Filete de pescado a la plancha c/ ensalada mixta', 26, 'Pescado', 'paradero'),
(gen_random_uuid(), 'Trucha frita c/ yuca frita y salsa criolla', 26, 'Pescado', 'paradero'),
(gen_random_uuid(), 'Chicharrón de pota completa', 20, 'Chicharrones y jaleas', 'paradero'),
(gen_random_uuid(), 'Chicharrón de pescado completo', 34, 'Chicharrones y jaleas', 'paradero'),
(gen_random_uuid(), 'Chicharrón de calamar', 35, 'Chicharrones y jaleas', 'paradero'),
(gen_random_uuid(), 'Jalea mixta', 45, 'Chicharrones y jaleas', 'paradero'),
(gen_random_uuid(), 'Jalea norteña + pescado entero', 55, 'Chicharrones y jaleas', 'paradero'),
(gen_random_uuid(), 'Alitas búfalo (6 piezas)', 22, 'Antojitos night', 'paradero'),
(gen_random_uuid(), 'Alitas BBQ (6 piezas)', 22, 'Antojitos night', 'paradero'),
(gen_random_uuid(), 'Alitas acebichadas', 25, 'Antojitos night', 'paradero'),
(gen_random_uuid(), 'Trío de alitas: búfalo + BBQ + acebichada', 49, 'Antojitos night', 'paradero'),
(gen_random_uuid(), 'Ensalada mixta c/ palta', 16, 'Dietético', 'paradero'),
(gen_random_uuid(), 'Ensalada suprema', 19, 'Dietético', 'paradero'),
(gen_random_uuid(), 'Camote glaseado', 5, 'Complementos', 'paradero'),
(gen_random_uuid(), 'Chifles', 5, 'Complementos', 'paradero'),
(gen_random_uuid(), 'Choclo', 5, 'Complementos', 'paradero'),
(gen_random_uuid(), 'Yuca frita', 5, 'Complementos', 'paradero'),
(gen_random_uuid(), 'Plátanos frito', 5, 'Complementos', 'paradero'),
(gen_random_uuid(), 'Yuyo frito', 5, 'Complementos', 'paradero'),
(gen_random_uuid(), 'Huevo frito', 3, 'Complementos', 'paradero'),
(gen_random_uuid(), 'Papa frita', 8, 'Complementos', 'paradero'),
(gen_random_uuid(), 'Porción de tortillas de choclo (6 und.)', 12, 'Complementos', 'paradero'),
(gen_random_uuid(), '1/4 de arroz c/ pato + huancaina', 30, 'Sábados, domingos y feriados', 'paradero'),
(gen_random_uuid(), '1/4 de arroz c/ pato + cebiche', 40, 'Sábados, domingos y feriados', 'paradero'),
(gen_random_uuid(), 'Seco de cordero / frijoles / yuca', 26, 'Sábados, domingos y feriados', 'paradero'),
(gen_random_uuid(), '1/2 cuy dorado', 40, 'Sábados, domingos y feriados', 'paradero'),
(gen_random_uuid(), 'Tallarines verdes con bisteck', 30, 'Sábados, domingos y feriados', 'paradero'),
(gen_random_uuid(), 'Malaya dorada c/ papa dorada', 22, 'Sábados, domingos y feriados', 'paradero'),
(gen_random_uuid(), 'Lomo saltado', 26, 'Parrillas', 'paradero'),
(gen_random_uuid(), 'Saltado de pollo', 24, 'Parrillas', 'paradero'),
(gen_random_uuid(), 'Tallarín saltado de pollo o carne', 25, 'Parrillas', 'paradero'),
(gen_random_uuid(), 'Tallarín a la huancaina c/ lomo saltado', 32, 'Parrillas', 'paradero'),
(gen_random_uuid(), 'Spaguetti c/ langostinos', 26, 'Parrillas', 'paradero'),
(gen_random_uuid(), 'Milanesa de pollo', 18, 'Parrillas', 'paradero'),
(gen_random_uuid(), 'Bisteck a lo pobre', 28, 'Parrillas', 'paradero'),
(gen_random_uuid(), 'Churrasco a la parrilla', 30, 'Parrillas', 'paradero'),
(gen_random_uuid(), 'Pollo a la plancha c/ papas fritas + ensalada mixta', 25, 'Parrillas', 'paradero'),
(gen_random_uuid(), 'Lomo chaufa', 28, 'Parrillas', 'paradero'),
(gen_random_uuid(), 'Chaufa de pollo o aeropuerto', 17, 'Saltados al wok', 'paradero'),
(gen_random_uuid(), 'Chaufa de la selva + plátano frito y ají de cocona', 24, 'Saltados al wok', 'paradero'),
(gen_random_uuid(), 'Tamalito verde (c/ salsa criolla)', 14, 'Piqueos', 'paradero'),
(gen_random_uuid(), 'Conchitas a la parmesana (6 und.)', 28, 'Piqueos', 'paradero'),
(gen_random_uuid(), 'Choros a la chalaca (6 und.)', 20, 'Piqueos', 'paradero'),
(gen_random_uuid(), 'Pulpo al olivo', 32, 'Piqueos', 'paradero'),
(gen_random_uuid(), 'Pulpo a la parrilla', 38, 'Piqueos', 'paradero'),
(gen_random_uuid(), '3 tortillas de choclo c/ cevichito', 20, 'Piqueos', 'paradero'),
(gen_random_uuid(), 'Pan c/ pejerrey', 12, 'Piqueos', 'paradero'),
(gen_random_uuid(), 'Tequeños / queso y guacamole 6 unidades', 12, 'Piqueos', 'paradero'),
(gen_random_uuid(), 'Tequeños / queso y guacamole 12 unidades', 24, 'Piqueos', 'paradero'),
(gen_random_uuid(), 'Causa de atún', 13, 'Causas', 'paradero'),
(gen_random_uuid(), 'Causa acebichada', 18, 'Causas', 'paradero'),
(gen_random_uuid(), 'Causa pulpa de cangrejo', 26, 'Causas', 'paradero'),
(gen_random_uuid(), 'Causa de langostinos', 26, 'Causas', 'paradero'),
(gen_random_uuid(), 'Causa pulpo al olivo', 26, 'Causas', 'paradero'),
(gen_random_uuid(), 'Cebiche de pescado', 28, 'Cebiches', 'paradero'),
(gen_random_uuid(), 'Cebiche mixto', 30, 'Cebiches', 'paradero'),
(gen_random_uuid(), 'Cebiche de pota/pescado', 22, 'Cebiches', 'paradero'),
(gen_random_uuid(), 'Cebiche de conchas (12 und.)', 45, 'Cebiches', 'paradero'),
(gen_random_uuid(), 'Cebiche purita pota', 20, 'Cebiches', 'paradero'),
(gen_random_uuid(), 'Cebiche clásico', 38, 'Cebiches', 'paradero'),
(gen_random_uuid(), 'Cebiche de pescado y 6 und. conchas negras', 35, 'Cebiches', 'paradero'),
(gen_random_uuid(), 'Leche de tigre de pescado + chicharrón de pota', 15, 'Leche de tigre', 'paradero'),
(gen_random_uuid(), 'Leche de pantera + chicharrón de pota', 19, 'Leche de tigre', 'paradero'),
(gen_random_uuid(), 'Leche de tigre mixta + chicharrón de pota', 21, 'Leche de tigre', 'paradero'),
(gen_random_uuid(), 'Leche de tigre Paradero 104', 26, 'Leche de tigre', 'paradero'),
(gen_random_uuid(), 'Tiradito clásico', 25, 'Tiradito', 'paradero'),
(gen_random_uuid(), 'Ronda 1°', 55, 'Piqueo marino', 'paradero'),
(gen_random_uuid(), 'Ronda 2°', 65, 'Piqueo marino', 'paradero'),
(gen_random_uuid(), 'Chicharrón de pota c/ chaufa de mariscos', 26, 'Piqueo marino', 'paradero'),
(gen_random_uuid(), 'Chicharrón de pota c/ arroz con mariscos', 26, 'Piqueo marino', 'paradero'),
(gen_random_uuid(), 'Chicharrón de pescado c/ arroz con mariscos', 28, 'Piqueo marino', 'paradero'),
(gen_random_uuid(), 'Chicharrón de pescado c/ chaufa de mariscos', 28, 'Piqueo marino', 'paradero'),
(gen_random_uuid(), 'Combina tu dúo', 35, 'Piqueo marino', 'paradero');